#!/bin/bash
echo ""
xsorcf=$1
#Customize the org and space to your own situation
#org="HANAExpress"
#org="LCFX"
org="A-Team_ml"
#space="delvelopment"
#space="DEV"
space="ml"
path=$2
proj="python-securestore"
app=$proj"_"$path
host=$app"-"$path
dowait=""
doexport1=""
doexport2=""
if [ "$#" -eq 2 ]; then
  if [ $xsorcf = "xs" ]; then
    dowait=" --wait-indefinitely"
    doexport1=" --export-json /dev/stdout 2>/dev/null | tail -n +5"
    echo "XS cool."
  else
    if [ $xsorcf = "cf" ]; then
      doexport1=" | tail -n +5 | head -n -8"
      doexport2=" | head -n -1"
      echo "CF cool."
    else
      echo "Not XS or CF, try again."
      exit 1
    fi
  fi

  echo Client Python $xsorcf Deploy into org: $org space: $space Starting 
  echo ""

  ss_instance=$proj"-ss"

  cmd=$xsorcf' service '$ss_instance
  echo $cmd
  eval $cmd
  RESULT=$?

  echo 'RESULT:'$RESULT

  service='hana'
  plan='securestore'

  if [ $RESULT -ne 0 ]; then
    cmd=$xsorcf' create-service '$service' '$plan' '$ss_instance
    echo $cmd
    eval $cmd

  fi
  
  cmd=$xsorcf' service '$ss_instance
  echo $cmd
  eval $cmd
  RESULT=$?

  echo 'SS CREATE RESULT:'$RESULT

  # Service creation is NOT guarenteed to happen right away
  while [ $RESULT -ne 0 ]; do
    sleep 30
    cmd=$xsorcf' service '$ss_instance
    echo $cmd
    eval $cmd
    RESULT=$?

    echo 'RESULT:'$RESULT
    # Handle CF creation of services a bit differently
    # cf services | grep dat368-hdi | grep "create succeeded"
  done 

  cmd=$xsorcf' push '$app' -k 1024M -m 256M -p '$path' --no-start'
  echo $cmd
  eval $cmd

  cmd=$xsorcf' bind-service '$app' '$ss_instance
  echo $cmd
  eval $cmd

  cmd=$xsorcf' restart '$app' '$dowait
  echo $cmd
  eval $cmd

  echo ""

  cmd='SS_SCHEMA=$('$xsorcf' env '$app' '$doexport1' | jq -r '"'"'.VCAP_SERVICES.hana[0].credentials.schema'"'"$doexport2')'
  #echo $cmd
  eval $cmd
  echo 'SS_SCHEMA='$SS_SCHEMA

  cmd='SS_USER=$('$xsorcf' env '$app' '$doexport1' | jq -r '"'"'.VCAP_SERVICES.hana[0].credentials.user'"'"$doexport2')'
  #echo $cmd
  eval $cmd
  echo 'SS_USER='$SS_USER

  cmd='SS_PASS=$('$xsorcf' env '$app' '$doexport1' | jq -r '"'"'.VCAP_SERVICES.hana[0].credentials.password'"'"$doexport2')'
  #echo $cmd
  eval $cmd
  echo 'SS_PASS='$SS_PASS

else
    echo "Usage ./py_deploy xs[cf] path"
    exit 1
fi
echo ""
echo Client HDI Deploy Finished
